"""Core protocol tooling for nostrain."""

from .aggregation import OuterStepResult, aggregate_deltas, nesterov_outer_step
from .compression import (
    CompressedGradientPayload,
    CompressionCodec,
    compress_delta,
    decompress_payload,
    inspect_payload,
)
from .crypto import schnorr_sign, schnorr_verify, secret_key_to_public_key
from .model import (
    ModelState,
    TensorLayout,
    TensorState,
    add_states,
    apply_delta,
    compute_delta,
    scale_state,
    state_digest,
    subtract_states,
    zeros_like,
)
from .protocol import (
    GradientEventMetadata,
    HeartbeatEventMetadata,
    NostrainEvent,
    ParsedGradientEvent,
    ParsedHeartbeatEvent,
    build_gradient_event,
    build_heartbeat_event,
    parse_heartbeat_event,
    parse_gradient_event,
    parse_nostrain_event,
)
from .relay import (
    CollectedGradientEvent,
    CollectedHeartbeatEvent,
    HeartbeatCollectionResult,
    RelayCollectionResult,
    RelayPublishResult,
    collect_heartbeat_events,
    collect_gradient_events,
    publish_heartbeat_event,
    publish_gradient_event,
    publish_nostrain_event,
)
from .training import (
    LINEAR_BIAS_PARAMETER,
    LINEAR_WEIGHT_PARAMETER,
    LinearModel,
    LinearModelAdapter,
    LinearRegressionDataset,
    LocalTrainingConfig,
    LocalTrainingResult,
    RegressionExample,
    TrainingRoundSummary,
    TrainingSessionResult,
    TrainingWorkerConfig,
    evaluate_linear_regression,
    run_training_session,
    train_linear_regression,
)

__all__ = [
    "CompressedGradientPayload",
    "CompressionCodec",
    "CollectedGradientEvent",
    "CollectedHeartbeatEvent",
    "GradientEventMetadata",
    "HeartbeatCollectionResult",
    "HeartbeatEventMetadata",
    "LINEAR_BIAS_PARAMETER",
    "LINEAR_WEIGHT_PARAMETER",
    "LinearModel",
    "LinearModelAdapter",
    "LinearRegressionDataset",
    "LocalTrainingConfig",
    "LocalTrainingResult",
    "ModelState",
    "NostrainEvent",
    "OuterStepResult",
    "ParsedGradientEvent",
    "ParsedHeartbeatEvent",
    "RegressionExample",
    "RelayCollectionResult",
    "RelayPublishResult",
    "TensorLayout",
    "TensorState",
    "TrainingRoundSummary",
    "TrainingSessionResult",
    "TrainingWorkerConfig",
    "add_states",
    "aggregate_deltas",
    "apply_delta",
    "build_gradient_event",
    "build_heartbeat_event",
    "compress_delta",
    "collect_heartbeat_events",
    "collect_gradient_events",
    "compute_delta",
    "decompress_payload",
    "evaluate_linear_regression",
    "inspect_payload",
    "nesterov_outer_step",
    "parse_heartbeat_event",
    "parse_gradient_event",
    "parse_nostrain_event",
    "publish_heartbeat_event",
    "publish_gradient_event",
    "publish_nostrain_event",
    "run_training_session",
    "scale_state",
    "schnorr_sign",
    "schnorr_verify",
    "secret_key_to_public_key",
    "state_digest",
    "subtract_states",
    "train_linear_regression",
    "zeros_like",
]

__version__ = "0.5.0"
